language: java
sudo: false
jdk:
- oraclejdk7

install:
- mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=5.0p
- mvn clean install -Pdev

notifications:
  email: false
  webhooks:
      urls: https://webhooks.gitter.im/e/b38a7fadad0c7821d365
      on_success: never
      on_failure: change
      on_start: never

