language: java
jdk: 
  - oraclejdk8
before_install:
  - mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=6.0p -DbuildDate=2017-01-11
  - mvn clean -q
  - mkdir ~/.meditor && cp -r resources/xml/ ~/.meditor
install: mvn install -q
sudo: false

notifications:
  email: false
  webhooks:
      urls: https://webhooks.gitter.im/e/b38a7fadad0c7821d365
      on_success: never
      on_failure: change
      on_start: never

