language: java
sudo: false
addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet
jdk:
  - oraclejdk8
before_install:
  - mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=6.0p -DbuildDate=`curl -s http://www.smartclient.com/builds/SmartGWT/6.0p/LGPL 2>&1 | xmlstarlet sel -t -c "//html/body/pre[2]/a[1]/text()"`
  - mvn clean -q
  - mkdir ~/.meditor && cp -r resources/xml/ ~/.meditor
install: mvn install --batch-mode

