language: java
jdk: 
  - oraclejdk7
  - oraclejdk8
before_install:
  - mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=5.0p -DbuildDate=2015-11-29
  - mkdir ~/.meditor && cp -r resources/xml/ ~/.meditor
install: mvn clean install
sudo: false

notifications:
  email: false
  webhooks:
      urls: https://webhooks.gitter.im/e/b38a7fadad0c7821d365
      on_success: never
      on_failure: change
      on_start: never

